package com.hospital.hms.util;

public class PdfLogoAssets {
    public static final String CADUCEUS_LOGO = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAAbklEQVR4nO3QMQ0AIBQEsKP8aQxCEwU7m4HO/iFpAgAAAAAAAPhpu9PXPesd3r4DAAAAAAAAAAAAeG67v++m7T5wJwAAAAAAAAAAAACAv/YAd74aP8Bv233n2+4b7wQAAAAAAAAAAADw3x5q0AItN20N/QAAAABJRU5ErkJggg==";
    public static final String SHIELD_LOGO = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAAbklEQVR4nO3QMQ0AIBQEsKP8aQxCEwU7m4HO/iFpAgAAAAAAAPhpu9PXPesd3r4DAAAAAAAAAAAAeG67v++m7T5wJwAAAAAAAAAAAACAv/YAd74aP8Bv233n2+4b7wQAAAAAAAAAAADw3x5q0AItN20N/QAAAABJRU5ErkJggg==";
}
